- hosts: droplet
  become: yes
  vars:
    droplet_ip: "{{ ansible_host }}"  # automatically uses the IP from your inventory

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install K3s (lightweight Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Wait for K3s to be ready
      shell: "k3s kubectl get nodes"
      register: result
      retries: 10
      delay: 5
      until: result.rc == 0

    - name: Update kubeconfig with droplet IP
      replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ droplet_ip }}:6443"

    - name: Export kubeconfig path for this session
      lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
        insertafter: EOF

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add ingress-nginx Helm repo
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update

    - name: Install ingress-nginx controller via Helm
      shell: |
        KUBECONFIG=/etc/rancher/k3s/k3s.yaml helm install nginx-ingress-controller ingress-nginx/ingress-nginx \
          --namespace my-ingress-release \
          --create-namespace \
          --set controller.service.type=NodePort \
          --set controller.service.nodePorts.http=32080 \
          --set controller.service.nodePorts.https=32443
      register: helm_result
      retries: 5
      delay: 10
      until: helm_result.rc == 0

